
font: &font Hack Nerd Font Mono:style=solid:size=12
font_icon: &font_icon Hack Nerd Font Mono:style=solid:size=20
std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

bar:
  background: 2E3440e5
  height: 32
  location: top
  margin: 0
  spacing: 5

  #border:
  #  width: 3
  #  color: 5e81acff
  #  margin: 5
  #  top-margin: 0

  # Default font
  font: *font

  left:
    - i3:
        sort: ascending
        anchors: # Not used (directly) by f00bar; used here to avoid duplication
          # TODO: make a universal tool for switching workspace
          #- string: &i3_common {margin: 5, on-click: "swaymsg --quiet workspace {name}"}
          - string: &i3_common {margin: 5, on-click: "i3-msg --quiet workspace {name}"}
          - string: &default     {<<: *i3_common, text: "? {name}"}
          - string: &main        {<<: *i3_common, text: , font: *font_icon}
          - string: &surfing     {<<: *i3_common, text: , font: *font_icon}
          - string: &misc        {<<: *i3_common, text: , font: *font_icon}
          - string: &mail        {<<: *i3_common, text: , font: *font_icon}
          - string: &music       {<<: *i3_common, text: , font: *font_icon}
          - string: &scratchpad  {<<: *i3_common, text: , font: *font_icon}
          - focused: &focused
              deco: {stack: [background: {color: ffa0a04c}, <<: *std_underline]}
          - invisible: &invisible {foreground: ffffff55}
          - urgent: &urgent
              foreground: 000000ff
              deco: {stack: [background: {color: bc2b3fff}, <<: *std_underline]}
          - map: &i3_mode
              tag: mode
              default:
                - string:
                    margin: 5
                    text: "{mode}"
                    deco: {background: {color: cc421dff}}
                - empty: {right-margin: 7}
              values:
                default: {empty: {}}
        content:
          "":
            map:
              tag: state
              values:
                focused:   {string: {<<: [*default, *focused]}}
                unfocused: {string: {<<: *default}}
                invisible: {string: {<<: [*default, *invisible]}}
                urgent:    {string: {<<: [*default, *urgent]}}
          ws1:
            map:
              tag: state
              values:
                focused:   {string: {<<: [*main, *focused]}}
                unfocused: {string: {<<: *main}}
                invisible: {string: {<<: [*main, *invisible]}}
                urgent:    {string: {<<: [*main, *urgent]}}
          ws2:
            map:
              tag: state
              values:
                focused: {string: {<<: [*surfing, *focused]}}
                unfocused: {string: {<<: *surfing}}
                invisible: {string: {<<: [*surfing, *invisible]}}
                urgent:    {string: {<<: [*surfing, *urgent]}}
          ws3:
            map:
              tag: state
              values:
                focused: {string: {<<: [*misc, *focused]}}
                unfocused: {string: {<<: *misc}}
                invisible: {string: {<<: [*misc, *invisible]}}
                urgent:    {string: {<<: [*misc, *urgent]}}
          ws4:
            map:
              tag: state
              values:
                focused: {string: {<<: [*music, *focused]}}
                unfocused: {string: {<<: *music}}
                invisible: {string: {<<: [*music, *invisible]}}
                urgent:    {string: {<<: [*music, *urgent]}}
          ws5:
            map:
              tag: state
              values:
                focused: {string: {<<: [*mail, *focused]}}
                unfocused: {string: {<<: *mail}}
                invisible: {string: {<<: [*mail, *invisible]}}
                urgent:    {string: {<<: [*mail, *urgent]}}
          ws99:
            map:
              tag: state
              values:
                focused: {string: {<<: [*scratchpad, *focused]}}
                unfocused: {string: {<<: *scratchpad}}
                invisible: {string: {<<: [*scratchpad, *invisible]}}
                urgent:    {string: {<<: [*scratchpad, *urgent]}}
          current:
            map:
              left-margin: 7
              tag: application
              values:
                "":
                  - map: {<<: *i3_mode}
                  - string: {text: "{title}"}
              default:
                list:
                  spacing: 0
                  items:
                    - map: {<<: *i3_mode}
                    - string: {text: "{application}", max: 10, foreground: ffa0a0ff}
                    - string: {text: ": "}
                    - string: {text: "{title}", max: 35}

  # TODO: ethernet

  right:
    - network:
        name: enp4s0
        content:
          map:
            tag: state
            default:
              string:
                text: 
                font: *font_icon
                foreground: ffffff66
            values:
              down:
                string:
                  text: 
                  font: *font_icon
                  foreground: ff0000ff
              up:
                map:
                  tag: ipv4
                  default:
                    - string:
                        text: 
                        font: *font_icon
                    - string:
                        text: "{ipv4}"
                        font: *font
                  values:
                    "":
                      string:
                        text: 
                        font: *font_icon
                        foreground: ffffff66

    - battery:
        name: BAT0
        poll-interval: 30
        content:
          map:
            tag: state
            values:
              discharging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff, font: *font_icon}
                      - string: {text: , foreground: ffa600ff, font: *font_icon}
                      - string: {text: , font: *font_icon}
                      - string: {text: , font: *font_icon}
                      - string: {text: , font: *font_icon}
                      - string: {text: , font: *font_icon}
                      - string: {text: , font: *font_icon}
                      - string: {text: , font: *font_icon}
                      - string: {text: , font: *font_icon}
                      - string: {text: , foreground: 00ff00ff, font: *font_icon}
                - string: {text: "{capacity}% {estimate}"}
              charging:
                - string: {text: , foreground: 00ff00ff, font: *font_icon}
                - string: {text: "{capacity}% {estimate}"}
              full:
                - string: {text: , foreground: 00ff00ff, font: *font_icon}
                - string: {text: "{capacity}% full"}

    - clock:
        content:
          - string: {text: , font: *font_icon}
          - string: {text: "{date}", right-margin: 7}
          - string: {text: , font: *font_icon}
          - string: {text: "{time}"}
